// COLD DEEP LINKS ONTO LAZY DESTINATIONS.
//
// index.html's inline boot script preloads the lazy bundle(s) a deep link needs (and
// starts that route's always-asked reads) while the eager set is still on the wire.
// Its route table is generated by the build from the route grammar, BUNDLES' `views`
// and the loader's own url/dependency tables (scripts/lazy-route-preload.mjs). What
// can go wrong: the committed shell drifts from the build, a view is declared under
// the wrong bundle, a preload url misses the one ensureBundle injects (a double
// download), or an early read is never taken (a wasted request).
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";
import { BUNDLES } from "../scripts/build-client.mjs";
import {
  LAZY_ROUTES_MARKER,
  SHELL_EARLY_READS,
  VIEW_EARLY_READS,
  bundleDigits,
  lazyRoutePreloadTable,
  viewBundleIndex,
  withLazyRouteTable,
} from "../scripts/lazy-route-preload.mjs";
import { earlyFetchScript } from "../dist/earlyFetch.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (file) => readFileSync(path.join(root, file), "utf8");
const html = read("public/index.html");
const table = lazyRoutePreloadTable(root, BUNDLES);

function routesApi() {
  const context = { URL, URLSearchParams, window: {}, globalThis: null };
  context.globalThis = context;
  context.window = context;
  vm.runInNewContext(read("public/js/route-state.js"), context);
  return context.CairnRoutes;
}

function canonicalRoutes() {
  const routes = routesApi();
  const defs = routes.routeDefinitions;
  const sections = new Set([
    ...Object.values(defs.sections).flat(),
    "session",
    "fuel",
    "plan",
    "race",
    "changes",
    "health",
    "settings",
  ]);
  const out = [];
  for (const home of defs.homes) {
    for (const section of ["", ...sections]) {
      const url = `/app/${home}${section ? `/${section}` : ""}?id=x`;
      const route = routes.parseRoute(url);
      if (!route.legacy) out.push({ url, route });
    }
  }
  return out;
}

test("the committed shell carries the table the build derives", () => {
  assert.ok(LAZY_ROUTES_MARKER.test(html), "index.html's boot script carries the generated table");
  assert.equal(withLazyRouteTable(html, table), html, "run npm run build and commit public/index.html");
});

test("every lazy bundle's views are exactly the ones render-dispatch loads it for", () => {
  const bundleOf = viewBundleIndex(BUNDLES);
  const dispatch = read("public/js/app-render-dispatch.js");
  const stub = () => undefined;
  let seen = 0;
  for (const { url, route } of canonicalRoutes()) {
    const asked = [];
    const context = {
      headerTitle: { classList: { remove: stub } },
      document: { getElementById: () => null, body: { classList: { remove: stub }, dataset: {} } },
      updateHeaderCondense: stub,
      state: { planSeg: route.tab === "plan" ? route.section : null, planJump: null },
      withBundle: (name) => asked.push(name),
      renderToday: stub,
      renderSession: stub,
      renderFoodJournal: stub,
      renderMeals: stub,
      renderYou: stub,
      window: {},
      globalThis: null,
    };
    context.globalThis = context;
    vm.runInNewContext(dispatch, context);
    context.renderTab(route.tab);
    assert.deepEqual(asked, bundleOf(route) ? [bundleOf(route)] : [], url);
    seen += 1;
  }
  assert.ok(seen > 20, "the route grammar was enumerated");
});

function lazyLoader() {
  const context = { window: {}, globalThis: null };
  context.globalThis = context;
  vm.runInNewContext(read("public/js/app-lazy-bundles.js"), context);
  return context;
}

test("a preload names the exact url ensureBundle injects, and the worker precaches it", () => {
  const { LAZY_BUNDLE_SRC } = lazyLoader();
  // Every lazy bundle a canonical route needs is preloadable. The meals bundle's route
  // is the week menu (/app/today/menu). Today's lower half (today-ahead) renders inside
  // the eager Today view, so it has no route; it is still precached and warmed first on
  // idle.
  // Sign-in (auth) is opened by a 401 or a Settings tap, never a route.
  const ROUTELESS = new Set([LAZY_BUNDLE_SRC["today-ahead"], LAZY_BUNDLE_SRC.auth]);
  assert.deepEqual(
    [...table.b].sort(),
    Object.values(LAZY_BUNDLE_SRC)
      .filter((url) => !ROUTELESS.has(url))
      .sort()
  );
  const sw = read("public/sw.js");
  for (const url of table.b) {
    assert.ok(!url.includes("?"), `${url} carries no query (it must hit the precache entry)`);
    assert.ok(sw.includes(`"${url}"`), `${url} is in CORE_ASSETS`);
  }
});

function runBoot({ pathname, profileRow, planRow, now = Date.UTC(2026, 8, 26, 12) }) {
  const links = [];
  const calls = [];
  const storage = {
    cairn_token: "",
    "cairn.swr.v1.profile": profileRow == null ? null : JSON.stringify(profileRow),
    "cairn.swr.v1.plan": planRow == null ? null : JSON.stringify(planRow),
  };
  const context = {
    location: { pathname },
    localStorage: { getItem: (key) => storage[key] ?? null },
    Intl: { DateTimeFormat: () => ({ resolvedOptions: () => ({ timeZone: "UTC" }) }) },
    document: {
      createElement: () => ({}),
      head: { appendChild: (node) => links.push(node) },
    },
    fetch: (url) => {
      calls.push(url);
      return Promise.resolve({ status: 200 });
    },
    Date: class extends Date {
      constructor(...args) {
        if (args.length) super(...args);
        else super(now);
      }
      static now() {
        return now;
      }
    },
  };
  context.window = context;
  vm.runInNewContext(earlyFetchScript(html), context);
  return { links, calls, early: context.__cairnEarly };
}

test("a Health deep link preloads Train then Me/Health and starts its leaf's one fan-in", () => {
  const { links, calls, early } = runBoot({ pathname: "/app/you/markers" });
  assert.deepEqual(
    links.map((l) => [l.rel, l.as, l.fetchPriority, l.href]),
    [
      // Train draws its movement rows with the day view's shared row, so its closure starts with calendar.
      ["preload", "script", "low", "/js/bundle-12-calendar.js"],
      ["preload", "script", "low", "/js/bundle-08-train.js"],
      ["preload", "script", "low", "/js/bundle-05-me-health.js"],
    ]
  );
  const reads = [...SHELL_EARLY_READS, "/you-health?leaf=markers", "/profile"];
  for (const [pathname, leaf] of [
    ["/app/you/share", "share"],
    ["/app/you/records", "records"],
    ["/app/you/health", "health"],
    ["/app/you/recovery", "health"],
  ]) {
    assert.deepEqual(
      runBoot({ pathname }).calls,
      [...SHELL_EARLY_READS, `/you-health?leaf=${leaf}`, "/profile"].map((p) => `/api${p}`),
      pathname
    );
  }
  assert.deepEqual(
    calls,
    reads.map((p) => `/api${p}`)
  );
  assert.deepEqual(Object.keys(early), reads);
});

test("Train, Horizon, Ask, Settings and the week menu preload their closure and start only the shell's reads", () => {
  const cases = {
    "/app/today/menu": ["/js/bundle-13-meals.js"],
    "/APP/Train": ["/js/bundle-12-calendar.js", "/js/bundle-08-train.js"],
    "/app/horizon": ["/js/bundle-12-calendar.js", "/js/bundle-08-train.js", "/js/bundle-09-horizon.js"],
    "/app/horizon/race": ["/js/bundle-12-calendar.js", "/js/bundle-08-train.js", "/js/bundle-09-horizon.js"],
    "/app/ask": ["/js/bundle-10-ask.js"],
    "/app/ask/changes": ["/js/bundle-10-ask.js"],
    // Settings → Agents "Connect" mounts the welcome bundle's sign-in panel.
    "/app/you/settings/agents": ["/js/bundle-15-welcome.js", "/js/bundle-11-settings.js"],
    "/app/you/profile": ["/js/bundle-12-calendar.js", "/js/bundle-08-train.js", "/js/bundle-05-me-health.js"],
    // The home-free day page (any date) preloads the calendar alone; an old alias under a
    // home falls back to that home's closure (which carries the calendar too).
    "/app/day/2026-10-08": ["/js/bundle-12-calendar.js"],
    "/app/horizon/day": ["/js/bundle-12-calendar.js", "/js/bundle-08-train.js", "/js/bundle-09-horizon.js"],
  };
  for (const [pathname, hrefs] of Object.entries(cases)) {
    const { links, calls } = runBoot({ pathname });
    assert.deepEqual(
      links.map((l) => l.href),
      hrefs,
      pathname
    );
    assert.deepEqual(
      calls,
      [...SHELL_EARLY_READS, "/profile"].map((p) => `/api${p}`),
      pathname
    );
  }
  const program = runBoot({ pathname: "/app/train/program" });
  assert.deepEqual(
    program.links.map((l) => l.href),
    ["/js/bundle-12-calendar.js", "/js/bundle-08-train.js"]
  );
  assert.deepEqual(
    program.calls,
    [...SHELL_EARLY_READS, "/train-home?view=program&date=2026-09-26", "/profile"].map((p) => `/api${p}`),
    "{date} is the device's local date, the one CairnTrainFanIn asks with"
  );
  const goalLine = runBoot({ pathname: "/app/horizon/goal" });
  assert.deepEqual(
    goalLine.calls,
    [...SHELL_EARLY_READS, "/train-home?view=goal&date=2026-09-26", "/profile"].map((p) => `/api${p}`),
    "a cold goal-line link starts its one fan-in with the shell's reads"
  );
  const plan = runBoot({ pathname: "/app/train/plan" });
  assert.deepEqual(
    plan.links.map((l) => l.href),
    ["/js/bundle-12-calendar.js", "/js/bundle-08-train.js"]
  );
  assert.deepEqual(
    plan.calls,
    [...SHELL_EARLY_READS, "/plan/week", "/plan/recovery-status", "/plan/upcoming", "/plan", "/profile"].map(
      (p) => `/api${p}`
    )
  );
});

test("/plan is asked early unless cachedApi would answer it from a row under 3 s old", () => {
  const now = Date.UTC(2026, 8, 26, 12);
  const young = runBoot({ pathname: "/app/train/plan", now, planRow: { data: [], ts: now - 2000 } });
  assert.ok(!young.calls.includes("/api/plan"));
  const older = runBoot({ pathname: "/app/train/plan", now, planRow: { data: [], ts: now - 3000 } });
  assert.ok(older.calls.includes("/api/plan"));
  const shapeless = runBoot({ pathname: "/app/train/plan", now, planRow: { ts: now } });
  assert.ok(shapeless.calls.includes("/api/plan"), "a row without data never peeks");
});

test("/profile is asked early only when primeDiscipline will ask for it", () => {
  const now = Date.UTC(2026, 8, 26, 12);
  const fresh = runBoot({
    pathname: "/app/train",
    now,
    profileRow: { data: { primary_discipline: "hybrid" }, ts: now - 60_000 },
  });
  assert.ok(!fresh.calls.includes("/api/profile"), "a remembered profile primes synchronously");
  const swept = runBoot({ pathname: "/app/train", now, profileRow: { data: { a: 1 }, ts: now - 25 * 3600_000 } });
  assert.ok(swept.calls.includes("/api/profile"), "a row the boot sweep evicts is asked for");
  const empty = runBoot({ pathname: "/app/train", now, profileRow: { data: null, ts: now } });
  assert.ok(empty.calls.includes("/api/profile"), "an empty row does not prime");
});

test("eager destinations, Today and nonsense paths preload nothing", () => {
  for (const pathname of [
    "/app/today/session",
    "/app/today/fuel",
    "/app/you",
    "/app/you/stone",
    "/constructor",
    "/app/constructor/x",
    "/x/y/z",
  ]) {
    const { links, calls } = runBoot({ pathname });
    assert.deepEqual(links, [], pathname);
    assert.deepEqual(calls, [], pathname);
  }
  const today = runBoot({ pathname: "/app/today" });
  assert.deepEqual(today.links, []);
  assert.equal(today.calls.length, 3, "Today keeps its own three reads");
});

test("a shell without a document still starts the reads", () => {
  const context = {
    location: { pathname: "/app/ask" },
    localStorage: { getItem: () => null },
    Intl: { DateTimeFormat: () => ({ resolvedOptions: () => ({ timeZone: "UTC" }) }) },
    fetch: () => Promise.resolve({ status: 200 }),
  };
  context.window = context;
  vm.runInNewContext(earlyFetchScript(html), context);
  assert.deepEqual(Object.keys(context.__cairnEarly), [...SHELL_EARLY_READS, "/profile"]);
});

// Each early read must be asked for, through api(), on every open of its route —
// otherwise its response is never taken and it costs a request.
test("the early reads are the ones the boot and each lazy view always ask for", () => {
  // Health: every Stand entry (cold or snapshot-warm, any section) primes the one
  // /you-health fan-in for its section's leaf before any view asks — so the early
  // request is that fan-in, never the reads it primes (a primed read never reaches
  // the wire, and an early copy of it would only be a second request).
  const stand = read("src/client/stand-screen.ts");
  const render = /async function renderStand\(\)[\s\S]*?\n {2}\}\n/.exec(stand)?.[0] || "";
  assert.match(
    render,
    /const seg = state\.standSeg \|\| null;\s*if \(typeof CairnHealthFanIn !== "undefined"\) CairnHealthFanIn\.prime\(seg\);/
  );
  const fanIn = read("src/client/health-fan-in-client.ts");
  assert.match(fanIn, /api\(`\/you-health\?leaf=\$\{leaf\}`/);
  assert.match(fanIn, /return s === "records" \|\| s === "markers" \|\| s === "share" \? s : "health";/);
  assert.deepEqual(VIEW_EARLY_READS.stand, ["/you-health?leaf=health"]);
  for (const leaf of ["records", "markers", "share"]) {
    assert.deepEqual(VIEW_EARLY_READS[`stand:${leaf}`], [`/you-health?leaf=${leaf}`]);
  }

  // The plan editor asks its three head reads on every first paint (a repaint reuses them).
  const head = read("src/client/plan-head-client.ts");
  const heads = /function planHeadReads\(\)[\s\S]*?\n\}/.exec(head)?.[0] || "";
  assert.deepEqual(
    [...heads.matchAll(/planHeadRead\("([^"]+)"\)/g)].map((m) => m[1]),
    VIEW_EARLY_READS["plan:edit"].slice(0, 3)
  );
  assert.deepEqual(VIEW_EARLY_READS["plan:edit"][3], ["/plan", "plan", 3000]);
  assert.match(
    read("src/client/plan-editor-controller.ts"),
    /const revalidate = cachedApi\("\/plan", \{\s*key: "plan",\s*onUpgrade/
  );
  assert.match(
    read("src/client/swr-cache.ts"),
    /const \{ key, freshFor = 60000, serveFreshFor = 3000, onUpgrade, project \} = options;/
  );
  assert.match(
    read("src/client/plan-editor-controller.ts"),
    /const heads: PlanHeadReads = reuseHeads \?\? CairnPlanHead\.headReads\(\);/
  );
  assert.match(
    read("src/client/plan-editor-controller.ts"),
    /async function renderPlanEditor\(\): Promise<void> \{\s*return paintPlanEditor\(\);/
  );
  assert.deepEqual(Object.keys(VIEW_EARLY_READS).sort(), [
    "horizon:goal",
    "plan:edit",
    "progress:program",
    "stand",
    "stand:markers",
    "stand:records",
    "stand:share",
  ]);

  // Train › Program: renderProgressProgram primes the /train-home fan-in for "program"
  // on every entry, before it asks for anything, with the device's local date.
  assert.deepEqual(VIEW_EARLY_READS["progress:program"], ["/train-home?view=program&date={date}"]);
  const program =
    /async function renderProgressProgram\([\s\S]*?\n\}\n/.exec(
      read("src/client/progress-program-controller.ts")
    )?.[0] || "";
  assert.match(program, /CairnTrainFanIn\.prime\("program"\)[\s\S]*?deps\s*\.api\("\/coaching-focus"\)/);
  // Horizon › Goal line primes the same fan-in for "goal" before its four reads.
  assert.deepEqual(VIEW_EARLY_READS["horizon:goal"], ["/train-home?view=goal&date={date}"]);
  const goal =
    /async function renderHorizonGoal\(\)[\s\S]*?\n {2}\}\n/.exec(read("src/client/horizon-screen.ts"))?.[0] || "";
  assert.match(goal, /CairnTrainFanIn\.prime\("goal"\)[\s\S]*?api\("\/journey"\)/);
  const train = read("src/client/train-fan-in-client.ts");
  assert.match(train, /const date = localISO\(\);/);
  assert.match(train, /const path = `\/train-home\?view=\$\{view\}&date=\$\{encodeURIComponent\(date\)\}`;/);
  assert.ok(earlyFetchScript(html).includes('q=q.replace("{date}",d);'), "the inline script fills {date}");

  const startup = read("src/client/app/startup.ts");
  for (const call of ["primeDiscipline();", "maybeOnboard();", "primeArtManifest();", "jobReconnect();"]) {
    assert.ok(startup.includes(call), `startAppShell calls ${call}`);
  }
  assert.match(
    read("src/client/app/onboarding.ts"),
    /async function maybeOnboard\(\)[\s\S]*?await api\("\/settings"\)/
  );
  assert.match(
    read("src/client/art-controller.ts"),
    /async function primeArtManifest\(\)[\s\S]*?await api\("\/art\/state"\)/
  );
  assert.match(
    read("src/client/agent-job-client.ts"),
    /async function jobReconnect\([^)]*\)[\s\S]*?await api\("\/agent-jobs"\)/
  );
  assert.deepEqual(SHELL_EARLY_READS, ["/settings", "/art/state", "/agent-jobs"]);

  // /profile: primeDiscipline asks only without a remembered "profile" row, and the
  // boot sweep drops rows older than a day — the inline script mirrors both.
  assert.match(
    read("src/client/app/discipline-primer.ts"),
    /peekCached<[^>]*>\("profile"\)[\s\S]*if \(warm && warm\.data\)[\s\S]*api\("\/profile"\)/
  );
  const swr = read("src/client/swr-cache.ts");
  assert.match(swr, /const SWR_NS = "cairn\.swr\.v1\.";/);
  assert.match(swr, /function swrSweep\(\): void \{\s*const MAX_AGE = 24 \* 60 \* 60 \* 1000;/);
  assert.ok(earlyFetchScript(html).includes('localStorage.getItem("cairn.swr.v1.profile")'));
  assert.ok(earlyFetchScript(html).includes("<=864e5"));
});

test("api() hands each early response over once, keyed by the path it is asked with", () => {
  const context = { globalThis: null, window: {} };
  context.globalThis = context;
  vm.runInNewContext(read("public/js/today-prefetch.js"), context);
  const res = Promise.resolve({ status: 200 });
  context.__cairnEarly = { "/markers/priority": { at: Date.now(), res } };
  assert.ok(context.CairnTodayPrefetch.takeEarly("/markers/priority"));
  assert.equal(context.CairnTodayPrefetch.takeEarly("/markers/priority"), undefined, "never twice");
});

test("a route's bundle string is one digit per index, and an 11th bundle url fails the build", () => {
  assert.equal(bundleDigits([0, 3, 9]), "039");
  assert.throws(() => bundleDigits([1, 10]), /not one digit/);
  assert.ok(table.b.length <= 10, "today's table fits the encoding");
});
