const expectation = (overrides = {}) => ({
  metric_key: "session_performance_feedback",
  subject_key: "next-session",
  direction: "maintain",
  baseline: { rating: "okay" },
  target: { rating: "okay_or_better" },
  window_start: "2026-07-13",
  window_end: "2026-08-10",
  minimum_data: { exposures: 2 },
  confounder_policy: "require_exposure",
  confidence: "tentative",
  evaluator: "session_feedback",
  evaluator_version: "brain-scenarios-v1",
  ...overrides,
});

const opinion = (domain, autonomyCeiling, evidenceKeys, overrides = {}) => ({
  domain,
  recommendation: "Keep the next step bounded and review the response.",
  rationale: "The current whole-person context favors a cautious, measurable decision.",
  evidence_keys: evidenceKeys,
  risks: [],
  contraindications: [],
  uncertainties: [],
  expected_outcomes: [],
  autonomy_ceiling: autonomyCeiling,
  ...overrides,
});

const decision = (overrides) => ({
  effective_date: "2026-07-13",
  status: "pending",
  rationale: "The current signals make this the smallest coherent next step.",
  source: "brain_scenario",
  source_ref_type: null,
  source_ref_key: null,
  reversible: true,
  context: { fixture: true },
  action: {},
  specialist: null,
  applied_at: null,
  reverted_at: null,
  superseded_by: null,
  evaluator_version: "brain-scenarios-v1",
  ...overrides,
});

export const BRAIN_SCENARIOS = Object.freeze([
  {
    id: "low-ferritin-endurance-fatigue",
    title: "Low ferritin during an endurance build with fatigue",
    timeline: [
      { date: "2026-06-01", event: "endurance_build_started" },
      { date: "2026-07-08", event: "low_ferritin_and_fatigue_observed" },
    ],
    facts: { low_ferritin: true, endurance_build: true, fatigue: true },
    decision: decision({
      kind: "health_directive",
      domain: "cross_domain",
      summary: "Hold progression and route the iron finding to clinician review.",
      autonomy_tier: "clinician",
      risk_class: "clinical",
    }),
    opinions: [
      opinion("health", "clinician", ["marker:ferritin:latest", "symptom:fatigue:recent"]),
      opinion("training", "ask", ["goal:endurance-build", "symptom:fatigue:recent"]),
    ],
    required_evidence_keys: ["marker:ferritin:latest", "goal:endurance-build", "symptom:fatigue:recent"],
    expected_contradictions: ["health_load_conflict"],
    question_count: 0,
  },
  {
    id: "apob-improving-body-composition",
    title: "Elevated ApoB while body composition is improving",
    timeline: [
      { date: "2026-05-15", event: "body_composition_trend_improved" },
      { date: "2026-07-01", event: "apob_remained_elevated" },
    ],
    facts: { elevated_apob: true, body_composition_improving: true },
    decision: decision({
      kind: "health_directive",
      domain: "cross_domain",
      summary: "Preserve the successful routine while keeping ApoB in clinician follow-up.",
      autonomy_tier: "clinician",
      risk_class: "clinical",
    }),
    opinions: [
      opinion("health", "clinician", ["marker:apob:latest", "body-composition:trend"], {
        uncertainties: ["Body-composition improvement does not establish the cause of ApoB movement."],
      }),
      opinion("nutrition", "observe", ["nutrition:pattern", "body-composition:trend"]),
    ],
    required_evidence_keys: ["marker:apob:latest", "body-composition:trend"],
    expected_contradictions: ["health_trajectory_conflict"],
    question_count: 0,
  },
  {
    id: "maintenance-must-not-drift",
    title: "Maintenance goal that must not drift into a deficit",
    timeline: [
      { date: "2026-06-20", event: "maintenance_goal_locked" },
      { date: "2026-07-06", event: "weight_noise_triggered_deficit_request" },
    ],
    facts: { goal_mode_maintain: true, requested_deficit: true },
    decision: decision({
      kind: "nutrition_target",
      domain: "nutrition",
      summary: "Keep calories at maintenance and gather another clean week.",
      autonomy_tier: "ask",
      risk_class: "moderate",
      action: { change: false },
    }),
    opinions: [opinion("nutrition", "ask", ["goal:maintenance", "weight-trend:21d", "intake:coverage:14d"])],
    required_evidence_keys: ["goal:maintenance", "weight-trend:21d"],
    expected_contradictions: ["goal_nutrition_conflict"],
    question_count: 0,
  },
  {
    id: "aggressive-loss-poor-recovery",
    title: "Aggressive fat-loss request with poor recovery and declining performance",
    timeline: [
      { date: "2026-06-10", event: "fat_loss_request" },
      { date: "2026-07-07", event: "recovery_and_performance_declined" },
    ],
    facts: { aggressive_fat_loss: true, poor_recovery: true, declining_performance: true },
    decision: decision({
      kind: "goal_change",
      domain: "cross_domain",
      summary: "Do not deepen the deficit; review recovery and goal pace first.",
      autonomy_tier: "ask",
      risk_class: "high",
    }),
    opinions: [
      opinion("nutrition", "ask", ["goal:fat-loss-request", "nutrition:current-target"]),
      opinion("recovery", "ask", ["recovery:14d", "performance:28d"]),
    ],
    required_evidence_keys: ["goal:fat-loss-request", "recovery:14d", "performance:28d"],
    expected_contradictions: ["fat_loss_recovery_conflict"],
    question_count: 0,
  },
  {
    id: "stalled-bench-sensitive-chest",
    title: "Stalled bench with chest or shoulder sensitivity",
    timeline: [
      { date: "2026-06-02", event: "bench_plateau_started" },
      { date: "2026-07-08", event: "sensitivity_reconfirmed" },
    ],
    facts: { stalled_bench: true, chest_or_shoulder_sensitivity: true, upper_body_loading: true },
    decision: decision({
      kind: "exercise_rotation",
      domain: "training",
      summary: "Rotate to a comfortable press variation without increasing load.",
      autonomy_tier: "quiet_apply",
      risk_class: "low",
      action: { movement: "comfortable_press_variation", load_increase: false },
    }),
    opinions: [
      opinion("training", "quiet_apply", ["exercise:bench:4-exposures", "symptom:chest-shoulder-sensitivity"], {
        contraindications: ["Do not progress load through pain."],
        expected_outcomes: [
          expectation({
            metric_key: "joint_pain_or_soreness",
            subject_key: "press-variation",
            direction: "avoid",
            target: { joint_pain: false },
            evaluator: "symptom_load",
          }),
        ],
      }),
    ],
    evaluation: {
      expectation_id: 1,
      verdict: "aligned",
      actual: { exposures: 3, joint_pain: false },
      evidence_keys: ["session-feedback:press:3-exposures"],
      confounders: [],
      explanation: "Three exposures were completed without reported joint pain.",
      evaluator_version: "brain-scenarios-v1",
    },
    required_evidence_keys: ["exercise:bench:4-exposures", "symptom:chest-shoulder-sensitivity"],
    expected_contradictions: ["loading_pain_conflict"],
    question_count: 0,
  },
  {
    id: "hscrp-after-hard-training",
    title: "High hs-CRP immediately after hard training",
    timeline: [
      { date: "2026-07-01", event: "hard_training_bout" },
      { date: "2026-07-02", event: "hscrp_draw_high" },
    ],
    facts: { elevated_hscrp: true, hard_training_recent: true },
    decision: decision({
      kind: "health_directive",
      domain: "health",
      summary: "Treat the isolated result as potentially transient and discuss retest timing.",
      autonomy_tier: "clinician",
      risk_class: "clinical",
    }),
    opinions: [
      opinion("health", "clinician", ["marker:hscrp:latest", "training:hard-session:prior-day"], {
        uncertainties: ["The draw timing may confound interpretation."],
      }),
    ],
    evaluation: {
      expectation_id: 2,
      verdict: "inconclusive",
      actual: { hscrp: "elevated" },
      evidence_keys: [],
      confounders: ["Hard training occurred immediately before the draw."],
      explanation: "The timing prevents a clean interpretation of the isolated value.",
      evaluator_version: "brain-scenarios-v1",
    },
    required_evidence_keys: ["marker:hscrp:latest", "training:hard-session:prior-day"],
    expected_contradictions: ["transient_marker_conflict"],
    question_count: 0,
  },
  {
    id: "travel-sparse-logging",
    title: "Travel week with sparse food and recovery logging",
    timeline: [
      { date: "2026-07-01", event: "trip_started" },
      { date: "2026-07-07", event: "logging_coverage_dropped" },
    ],
    facts: { travel: true, sparse_logging: true },
    decision: decision({
      kind: "day_read",
      domain: "cross_domain",
      summary: "Keep the week flexible and avoid inferring a new baseline.",
      autonomy_tier: "ask",
      risk_class: "moderate",
      action: { question: "Do you want a light travel-week template, or should I leave the week open?" },
    }),
    opinions: [opinion("lifestyle", "ask", ["context:trip", "logging:coverage:7d"])],
    evaluation: {
      expectation_id: 3,
      verdict: "inconclusive",
      actual: { logging_days: 2 },
      evidence_keys: [],
      confounders: ["Travel and sparse logging overlap the whole window."],
      explanation: "There is not enough comparable data to judge the response.",
      evaluator_version: "brain-scenarios-v1",
    },
    required_evidence_keys: ["context:trip", "logging:coverage:7d"],
    expected_contradictions: ["data_coverage_conflict"],
    question_count: 1,
  },
  {
    id: "medication-supplement-organ-markers",
    title: "Medication or supplement interaction with kidney or liver markers",
    timeline: [
      { date: "2026-05-01", event: "medication_and_supplement_recorded" },
      { date: "2026-07-03", event: "kidney_or_liver_marker_flagged" },
    ],
    facts: { medication_or_supplement_change: true, kidney_or_liver_marker: true },
    decision: decision({
      kind: "health_directive",
      domain: "health",
      summary: "Do not change medication or supplement dosing; prepare a clinician discussion.",
      autonomy_tier: "clinician",
      risk_class: "clinical",
      reversible: false,
    }),
    opinions: [
      opinion("health", "clinician", ["medication:list", "supplement:list", "marker:kidney-liver:latest"], {
        contraindications: ["No autonomous medication or supplement dose change."],
      }),
    ],
    required_evidence_keys: ["medication:list", "supplement:list", "marker:kidney-liver:latest"],
    expected_contradictions: ["clinical_interaction_conflict"],
    question_count: 0,
  },
  {
    id: "strength-race-goal-conflict",
    title: "Conflicting strength and race goals",
    timeline: [
      { date: "2026-05-10", event: "strength_goal_set" },
      { date: "2026-07-04", event: "race_goal_added_without_more_capacity" },
    ],
    facts: { strength_goal: true, race_goal: true, limited_weekly_capacity: true },
    decision: decision({
      kind: "goal_change",
      domain: "cross_domain",
      summary: "Ask which goal leads this block before changing the weekly structure.",
      autonomy_tier: "ask",
      risk_class: "moderate",
      action: { question: "Which matters more for this block: the race result or strength progression?" },
    }),
    opinions: [
      opinion("training", "ask", ["goal:strength", "goal:race", "availability:weekly"]),
      opinion("lifestyle", "ask", ["availability:weekly", "recovery:baseline"]),
    ],
    required_evidence_keys: ["goal:strength", "goal:race", "availability:weekly"],
    expected_contradictions: ["goal_capacity_conflict"],
    question_count: 1,
  },
  {
    id: "thin-data-uncertainty",
    title: "Thin-data user where uncertainty and one question are correct",
    timeline: [
      { date: "2026-07-07", event: "profile_created" },
      { date: "2026-07-08", event: "single_ambiguous_checkin" },
    ],
    facts: { thin_data: true },
    decision: decision({
      kind: "session_suggestion",
      domain: "cross_domain",
      summary: "Do not infer a program change; ask one question about the immediate constraint.",
      autonomy_tier: "ask",
      risk_class: "moderate",
      action: { question: "Is pain, time, or low energy the main thing shaping today's session?" },
    }),
    opinions: [
      opinion("training", "ask", ["data-coverage:training"], {
        uncertainties: ["No usable training history or recovery baseline is available."],
      }),
    ],
    evaluation: {
      expectation_id: 4,
      verdict: "inconclusive",
      actual: null,
      evidence_keys: [],
      confounders: ["Insufficient baseline and no repeated exposure."],
      explanation: "The available snapshot cannot support a directional conclusion.",
      evaluator_version: "brain-scenarios-v1",
    },
    required_evidence_keys: ["data-coverage:training"],
    expected_contradictions: ["insufficient_evidence"],
    question_count: 1,
  },
]);
