export type ClientApiContractPattern = string;

export interface ClientApiUnknownWaiver {
  pattern: string;
  owner: string;
  reason: string;
}

export interface ClientApiBroadResponseWaiver {
  pattern: string;
  owner: string;
  reason: string;
}

export const CLIENT_API_CONTRACT_PATHS = [
  "/health",
  "/version",
  "/update-status",
  "/update-check",
  "/settings",
  "/agents",
  "/agent-stats",
  "/agent-clis/update",
  "/art/manifest",
  "/art/stats",
  "/profile",
  "/goal",
  "/bodyweight",
  "/blood-pressure",
  "/checkins",
  "/plan",
  "/plan/:day",
  "/plan/:day/target",
  "/exercises",
  "/exercises/:id",
  "/exercises/:name",
  "/exercise/:name",
  "/exercise/:name/explanation",
  "/exercises/reconcile-names",
  "/sessions",
  "/sessions/:id",
  "/sessions/:id/finish",
  "/sessions/:id/reopen",
  "/sessions/:id/notes",
  "/sessions/:date/feedback",
  "/sessions/skip",
  "/sets",
  "/sets/:id",
  "/last-set",
  "/progress/:exercise",
  "/activities",
  "/activities/:id",
  "/agent/run",
  "/garmin/daily",
  "/garmin/unreconciled",
  "/garmin/reconcile",
  "/garmin/sync",
  "/recent-training",
  "/stats",
  "/endurance-prs",
  "/run-compliance",
  "/cardio",
  "/endurance-goal",
  "/volume",
  "/calendar",
  "/today-read",
  "/today-read/reshape",
  "/session-suggest",
  "/week-ahead",
  "/today-agenda",
  "/learned-timeline",
  "/since-last",
  "/guidelines",
  "/nutrition/day",
  "/nutrition/expenditure",
  "/nutrition/checkin",
  "/coach/mealplan",
  "/mealplans",
  "/mealplans/:id/accept",
  "/mealplans/:id/discard",
  "/meal-plans/:id/swap",
  "/meal-plans/:id/recipe",
  "/meal-plans/:id/days",
  "/food-notes",
  "/food-notes/:id",
  "/frequent-foods",
  "/proposals",
  "/proposals/:id/apply",
  "/proposals/:id/discard",
  "/program/evolve",
  "/program/progression",
  "/program/progression/apply",
  "/program/balance",
  "/program/adjustments",
  "/program/blocks",
  "/program/blocks/active",
  "/program-state",
  "/performance",
  "/run-plan",
  "/run-zones",
  "/muscle-trajectory",
  "/test-week",
  "/dexa-targeting",
  "/program/run-plan/apply",
  "/coaching-focus",
  "/health/markers",
  "/markers/priority",
  "/health/standing",
  "/health/review",
  "/health/synthesis",
  "/directives",
  "/directives/:id",
  "/directives/derive",
  "/markers/reconcile",
  "/recovery",
  "/symptom-links",
  "/evidence",
  "/evidence/summary",
  "/insights",
  "/insights/generate",
  "/insights/:id",
  "/health-docs",
  "/health-docs/:id",
  "/health-docs/:id/reanalyze",
  "/context-events",
  "/context-events/:id",
  "/injury-impacts",
  "/family",
  "/family/:id",
  "/learnings",
  "/memory",
  "/memory/:id",
  "/memory/:id/supersede",
  "/supplements",
  "/supplements/:id",
  "/supplements/understand",
  "/onboard",
  "/chat",
  "/chat/search",
  "/chat/sessions",
  "/chat/sessions/:sessionId",
  "/chat/turns",
  "/chat/turns/:id",
  "/chat/turns/:id/cancel",
  "/chat/reset",
  "/agent-jobs",
  "/agent-jobs/:id",
  "/agent-jobs/:id/cancel",
  "/agents/:name/info",
  "/agents/:name/models",
] as const satisfies readonly ClientApiContractPattern[];

export const CLIENT_API_UNKNOWN_WAIVERS = [] as const satisfies readonly ClientApiUnknownWaiver[];

export const CLIENT_API_BROAD_RESPONSE_WAIVERS = [
  {
    pattern: "/exercises/reconcile-names",
    owner: "Plan exercise reconciliation",
    reason: "Agent merge details are operator-facing and still need a narrow reconciliation result DTO.",
  },
  {
    pattern: "/recent-training",
    owner: "Training log client",
    reason: "Recent training feeds mixed session/activity summaries until the Training client owns a typed union.",
  },
  {
    pattern: "/endurance-prs",
    owner: "Endurance progress client",
    reason: "PR buckets are grouped by distance and need a dedicated endurance records DTO.",
  },
  {
    pattern: "/run-compliance",
    owner: "Endurance progress client",
    reason: "Compliance summary still mirrors the broad backend read until the run-plan screen narrows it.",
  },
  {
    pattern: "/cardio",
    owner: "Cardio planning client",
    reason: "Cardio rows include planned and logged variants that should become a typed discriminated union.",
  },
  {
    pattern: "/endurance-goal",
    owner: "Endurance progress client",
    reason: "Goal metadata is broad while discipline-specific target fields are still evolving.",
  },
  {
    pattern: "/week-ahead",
    owner: "Day coach client",
    reason: "Week-ahead combines deterministic and agent text until the day-coach payload is narrowed.",
  },
  {
    pattern: "/guidelines",
    owner: "Connected-brain evidence",
    reason: "Guideline packs are keyed records of trusted references and need a client-safe map DTO.",
  },
  {
    pattern: "/program-state",
    owner: "Agentic training brain",
    reason: "Program state is a large coach-context read and needs a shared deterministic DTO.",
  },
  {
    pattern: "/performance",
    owner: "Agentic training brain",
    reason: "Performance standing is a large deterministic read and needs a shared client-safe DTO.",
  },
  {
    pattern: "/health/standing",
    owner: "Health standing client",
    reason: "Standing combines body composition, BP, age references, and momentum until the Health DTO is split.",
  },
  {
    pattern: "/injury-impacts",
    owner: "Personal context client",
    reason: "Injury impact metadata is a keyed advisory map and needs a small typed record.",
  },
] as const satisfies readonly ClientApiBroadResponseWaiver[];
