export type ClientApiContractPattern = string;

export interface ClientApiUnknownWaiver {
  pattern: string;
  owner: string;
  reason: string;
}

export const CLIENT_API_CONTRACT_PATHS = [
  "/health",
  "/version",
  "/update-status",
  "/update-check",
  "/settings",
  "/agents",
  "/agent-stats",
  "/agent-clis/update",
  "/profile",
  "/goal",
  "/bodyweight",
  "/blood-pressure",
  "/checkins",
  "/plan",
  "/plan/:day",
  "/plan/:day/target",
  "/exercises",
  "/exercises/:id",
  "/exercises/:name",
  "/exercise/:name",
  "/exercise/:name/explanation",
  "/exercises/reconcile-names",
  "/sessions",
  "/sessions/:id",
  "/sessions/:id/finish",
  "/sessions/:id/reopen",
  "/sessions/:id/notes",
  "/sessions/:date/feedback",
  "/sessions/skip",
  "/sets",
  "/sets/:id",
  "/last-set",
  "/progress/:exercise",
  "/activities",
  "/activities/:id",
  "/recent-training",
  "/stats",
  "/endurance-prs",
  "/run-compliance",
  "/cardio",
  "/endurance-goal",
  "/today-read",
  "/today-read/reshape",
  "/session-suggest",
  "/week-ahead",
  "/today-agenda",
  "/learned-timeline",
  "/since-last",
  "/guidelines",
  "/nutrition/day",
  "/nutrition/expenditure",
  "/nutrition/checkin",
  "/mealplans",
  "/mealplans/:id/accept",
  "/mealplans/:id/discard",
  "/meal-plans/:id/days",
  "/food-notes",
  "/food-notes/:id",
  "/frequent-foods",
  "/proposals",
  "/proposals/:id/apply",
  "/proposals/:id/discard",
  "/program/progression",
  "/program/progression/apply",
  "/program/balance",
  "/program/adjustments",
  "/program/blocks",
  "/program/blocks/active",
  "/program-state",
  "/performance",
  "/run-plan",
  "/run-zones",
  "/muscle-trajectory",
  "/test-week",
  "/dexa-targeting",
  "/program/run-plan/apply",
  "/coaching-focus",
  "/health/markers",
  "/health/standing",
  "/health/review",
  "/health/synthesis",
  "/directives",
  "/directives/:id",
  "/directives/derive",
  "/markers/reconcile",
  "/symptom-links",
  "/evidence",
  "/evidence/summary",
  "/insights",
  "/insights/:id",
  "/health-docs",
  "/health-docs/:id",
  "/health-docs/:id/reanalyze",
  "/context-events",
  "/context-events/:id",
  "/injury-impacts",
  "/family",
  "/family/:id",
  "/memory",
  "/memory/:id",
  "/supplements",
  "/supplements/:id",
  "/supplements/understand",
  "/onboard",
  "/chat",
  "/chat/search",
  "/chat/sessions",
  "/chat/sessions/:sessionId",
  "/chat/turns",
  "/chat/turns/:id",
  "/chat/turns/:id/cancel",
  "/chat/reset",
  "/agent-jobs",
  "/agent-jobs/:id",
  "/agent-jobs/:id/cancel",
] as const satisfies readonly ClientApiContractPattern[];

export const CLIENT_API_UNKNOWN_WAIVERS = [
  {
    pattern: "/art/manifest",
    owner: "Wave 6 Shell/visual assets",
    reason: "Art manifest is a static asset inventory read; type it when the shell/art surface moves under src/client.",
  },
  {
    pattern: "/art/stats",
    owner: "Wave 6 Settings/system screen",
    reason: "Operator-only art telemetry stays screen-local until Settings is migrated from classic JS.",
  },
  {
    pattern: "/garmin/sync",
    owner: "Wave 6 Settings/Garmin screen",
    reason: "Garmin sync returns connector-specific telemetry; type with the Settings and Garmin screen migration.",
  },
  {
    pattern: "/garmin/daily",
    owner: "Wave 6 Today/Garmin screen",
    reason: "Garmin daily rows are still rendered from a classic screen-local shape.",
  },
  {
    pattern: "/garmin/unreconciled",
    owner: "Wave 6 Today/Garmin screen",
    reason: "Garmin reconciliation rows are still screen-local until the Today reconciliation module is typed.",
  },
  {
    pattern: "/garmin/reconcile",
    owner: "Wave 6 Today/Garmin screen",
    reason: "Garmin reconciliation result is connector-specific and will be typed with the reconciliation UI.",
  },
  {
    pattern: "/agents/:name/info",
    owner: "Wave 5 Shell/Settings jobs",
    reason: "Per-agent probe output depends on the installed CLI and remains intentionally loose until Settings is typed.",
  },
  {
    pattern: "/agents/:name/models",
    owner: "Wave 5 Shell/Settings jobs",
    reason: "Per-agent model listings depend on the installed CLI and remain intentionally loose until Settings is typed.",
  },
  {
    pattern: "/learnings",
    owner: "Wave 8 Memory contract",
    reason: "Outcome-learning projection belongs with the typed memory/agentic-brain contract wave.",
  },
] as const satisfies readonly ClientApiUnknownWaiver[];
