export type ClientApiContractPattern = string;

export interface ClientApiUnknownWaiver {
  pattern: string;
  owner: string;
  reason: string;
}

export interface ClientApiBroadResponseWaiver {
  pattern: string;
  owner: string;
  reason: string;
}

export const CLIENT_API_CONTRACT_PATHS = [
  "/health",
  "/ready",
  "/version",
  "/update-status",
  "/update-check",
  "/settings",
  "/agents",
  "/agent-stats",
  "/brain-diagnostics",
  "/diagnostics",
  "/telemetry/client",
  "/brain/decisions",
  "/brain/decisions/:id/revert",
  "/agent-clis/update",
  "/agent-clis/:name/install",
  "/art/manifest",
  "/art/stats",
  "/apple-health/config",
  "/apple-health/connections",
  "/apple-health/connections/:id",
  "/apple-health/pairings",
  "/profile",
  "/goal",
  "/bodyweight",
  "/body-metrics",
  "/body-metrics/trends",
  "/blood-pressure",
  "/checkins",
  "/plan",
  "/plan/:day",
  "/plan/:day/target",
  "/exercises",
  "/exercises/:id",
  "/exercises/:name",
  "/exercise/:name",
  "/exercise/:name/explanation",
  "/exercises/reconcile-names",
  "/sessions",
  "/sessions/:id",
  "/sessions/:id/finish",
  "/sessions/:id/reopen",
  "/sessions/:id/notes",
  "/sessions/:id/highlights",
  "/sessions/:date/feedback",
  "/sessions/skip",
  "/sets",
  "/sets/:id",
  "/last-set",
  "/progress/:exercise",
  "/strength-journey",
  "/strength-journey/suggestion/dismiss",
  "/activities",
  "/activities/:id",
  "/agent/run",
  "/garmin/daily",
  "/garmin/unreconciled",
  "/garmin/reconcile",
  "/garmin/sync",
  "/recent-training",
  "/stats",
  "/training-load",
  "/endurance-prs",
  "/run-compliance",
  "/cardio",
  "/endurance-goal",
  "/volume",
  "/calendar",
  "/week-wins",
  "/today",
  "/today-plan-day",
  "/today-read",
  "/today-read/reshape",
  "/session-suggest",
  "/session-primer",
  "/week-ahead",
  "/today-agenda",
  "/today-agenda/ack",
  "/learned-timeline",
  "/team-week",
  "/since-last",
  "/guidelines",
  "/nutrition/day",
  "/nutrition/expenditure",
  "/nutrition/checkin",
  "/nutrition/goal-pace",
  "/nutrition/fueling-followup",
  "/nutrition/fueling-feedback",
  "/coach/mealplan",
  "/mealplans",
  "/mealplans/:id/accept",
  "/mealplans/:id/discard",
  "/meal-plans/:id/swap",
  "/meal-plans/:id/recipe",
  "/meal-plans/:id/days",
  "/food-notes",
  "/food-notes/:id",
  "/frequent-foods",
  "/proposals",
  "/proposals/:id/apply",
  "/proposals/:id/discard",
  "/program/evolve",
  "/program/progression",
  "/program/progression/apply",
  "/program/swap",
  "/program/swap/apply",
  "/program/balance",
  "/program/adjustments",
  "/program/blocks",
  "/program/blocks/active",
  "/program-state",
  "/performance",
  "/run-plan",
  "/run-zones",
  "/muscle-trajectory",
  "/test-week",
  "/dexa-targeting",
  "/program/run-plan/apply",
  "/coaching-focus",
  "/health/markers",
  "/markers/priority",
  "/health/standing",
  "/health/risk",
  "/health/review",
  "/health/synthesis",
  "/directives",
  "/directives/:id",
  "/directives/derive",
  "/markers/reconcile",
  "/recovery",
  "/recovery/baseline",
  "/symptom-links",
  "/evidence",
  "/evidence/summary",
  "/insights",
  "/insights/generate",
  "/insights/:id",
  "/health-docs",
  "/health-docs/:id",
  "/health-docs/:id/reanalyze",
  "/health-docs/:id/confirm",
  "/context-events",
  "/context-events/:id",
  "/injury-impacts",
  "/family",
  "/family/:id",
  "/learnings",
  "/memory",
  "/memory/:id",
  "/memory/:id/supersede",
  "/supplements",
  "/supplements/:id",
  "/supplements/understand",
  "/onboard",
  "/chat",
  "/chat/search",
  "/chat/sessions",
  "/chat/sessions/:sessionId",
  "/chat/turns",
  "/chat/turns/:id",
  "/chat/turns/:id/cancel",
  "/chat/reset",
  "/agent-jobs",
  "/agent-jobs/:id",
  "/agent-jobs/:id/cancel",
  "/agents/:name/info",
  "/agents/:name/models",
] as const satisfies readonly ClientApiContractPattern[];

export const CLIENT_API_UNKNOWN_WAIVERS = [] as const satisfies readonly ClientApiUnknownWaiver[];

export const CLIENT_API_BROAD_RESPONSE_WAIVERS = [] as const satisfies readonly ClientApiBroadResponseWaiver[];
