#!/usr/bin/env node
// Compile dependency-free browser client slices from src/client into stable
// public/js filenames. This is intentionally explicit during migration: no
// bundler, no runtime deps, and no surprise asset names for the service worker.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";

const currentFile = fileURLToPath(import.meta.url);
const root = path.resolve(path.dirname(currentFile), "..");

export const CLIENT_OUTPUTS = [
  { source: "src/client/date-utils.ts", output: "public/js/date-utils.js" },
  { source: "src/client/html-utils.ts", output: "public/js/html-utils.js" },
  { source: "src/client/markdown-client.ts", output: "public/js/markdown-client.js" },
  { source: "src/client/ui-components.ts", output: "public/js/ui-components.js" },
  { source: "src/client/ui-reads.ts", output: "public/js/ui-reads.js" },
  { source: "src/client/ui-feedback-client.ts", output: "public/js/ui-feedback-client.js" },
  { source: "src/client/ui-actions-client.ts", output: "public/js/ui-actions-client.js" },
  { source: "src/client/ui-view-transitions-client.ts", output: "public/js/ui-view-transitions-client.js" },
  { source: "src/client/exercise-detail-client.ts", output: "public/js/exercise-detail-client.js" },
  { source: "src/client/format-utils.ts", output: "public/js/format-utils.js" },
  { source: "src/client/client-diagnostics.ts", output: "public/js/client-diagnostics.js" },
  { source: "src/client/api-client.ts", output: "public/js/api-client.js" },
  { source: "src/client/app/download.ts", output: "public/js/app-download.js" },
  { source: "src/client/app/sw-recovery.ts", output: "public/js/app-sw-recovery.js" },
  { source: "src/client/app/state.ts", output: "public/js/01-core.js" },
  { source: "src/client/cairn-body-figure.ts", output: "public/cairn-body-figure.js" },
  { source: "src/client/art-controller.ts", output: "public/js/art-controller.js" },
  { source: "src/client/ui-header-client.ts", output: "public/js/ui-header-client.js" },
  { source: "src/client/ui-segments-client.ts", output: "public/js/ui-segments-client.js" },
  { source: "src/client/ui-shell.ts", output: "public/js/02-ui.js" },
  { source: "src/client/detail-overlay-client.ts", output: "public/js/detail-overlay-client.js" },
  { source: "src/client/ui-motion-client.ts", output: "public/js/ui-motion-client.js" },
  { source: "src/client/exercise-detail-data-client.ts", output: "public/js/exercise-detail-data-client.js" },
  { source: "src/client/exercise-detail-explanation-client.ts", output: "public/js/exercise-detail-explanation-client.js" },
  { source: "src/client/exercise-detail-render-client.ts", output: "public/js/exercise-detail-render-client.js" },
  { source: "src/client/exercise-detail-actions-client.ts", output: "public/js/exercise-detail-actions-client.js" },
  { source: "src/client/exercise-detail-controller.ts", output: "public/js/exercise-detail-controller.js" },
  { source: "src/client/agent-login-model-client.ts", output: "public/js/agent-login-model-client.js" },
  { source: "src/client/agent-login-assets-client.ts", output: "public/js/agent-login-assets-client.js" },
  { source: "src/client/agent-login-modal-client.ts", output: "public/js/agent-login-modal-client.js" },
  { source: "src/client/agent-login-session-client.ts", output: "public/js/agent-login-session-client.js" },
  { source: "src/client/agent-login-client.ts", output: "public/js/agent-login-client.js" },
  { source: "src/client/agent-job-records-client.ts", output: "public/js/agent-job-records-client.js" },
  { source: "src/client/agent-job-client.ts", output: "public/js/agent-job-client.js" },
  { source: "src/client/pwa-install-coach.ts", output: "public/js/pwa-install-coach.js" },
  { source: "src/client/rest-timer.ts", output: "public/js/rest-timer.js" },
  { source: "src/client/coaching-focus-client.ts", output: "public/js/coaching-focus-client.js" },
  { source: "src/client/today-activity-client.ts", output: "public/js/today-activity-client.js" },
  { source: "src/client/save-bar.ts", output: "public/js/save-bar.js" },
  { source: "src/client/swr-cache.ts", output: "public/js/swr-cache.js" },
  { source: "src/client/today-agenda-client.ts", output: "public/js/today-agenda-client.js" },
  { source: "src/client/today-rail-loaders-client.ts", output: "public/js/today-rail-loaders-client.js" },
  { source: "src/client/today-rail-controller.ts", output: "public/js/today-rail-controller.js" },
  { source: "src/client/today-plan-selection-client.ts", output: "public/js/today-plan-selection-client.js" },
  { source: "src/client/today-training-client.ts", output: "public/js/today-training-client.js" },
  { source: "src/client/today-progression-controller.ts", output: "public/js/today-progression-controller.js" },
  { source: "src/client/today-add-exercise-controller.ts", output: "public/js/today-add-exercise-controller.js" },
  { source: "src/client/today-brief-client.ts", output: "public/js/today-brief-client.js" },
  { source: "src/client/today-brief-override-client.ts", output: "public/js/today-brief-override-client.js" },
  { source: "src/client/today-brief-actions-client.ts", output: "public/js/today-brief-actions-client.js" },
  { source: "src/client/today-brief-controller.ts", output: "public/js/today-brief-controller.js" },
  { source: "src/client/cardio-plan-client.ts", output: "public/js/cardio-plan-client.js" },
  { source: "src/client/cardio-sync-client.ts", output: "public/js/cardio-sync-client.js" },
  { source: "src/client/today-lately-client.ts", output: "public/js/today-lately-client.js" },
  { source: "src/client/proposal-client.ts", output: "public/js/proposal-client.js" },
  { source: "src/client/today-session-suggest-client.ts", output: "public/js/today-session-suggest-client.js" },
  { source: "src/client/today-session-suggest-controller.ts", output: "public/js/today-session-suggest-controller.js" },
  { source: "src/client/today-session-status-client.ts", output: "public/js/today-session-status-client.js" },
  { source: "src/client/today-session-feedback-client.ts", output: "public/js/today-session-feedback-client.js" },
  { source: "src/client/session-primer-client.ts", output: "public/js/session-primer-client.js" },
  { source: "src/client/today-session-skip-client.ts", output: "public/js/today-session-skip-client.js" },
  { source: "src/client/today-session-set-model.ts", output: "public/js/today-session-set-model.js" },
  { source: "src/client/today-session-set-actions.ts", output: "public/js/today-session-set-actions.js" },
  { source: "src/client/today-session-controller.ts", output: "public/js/today-session-controller.js" },
  { source: "src/client/today-cards-client.ts", output: "public/js/today-cards-client.js" },
  { source: "src/client/today-program-adjustments-client.ts", output: "public/js/today-program-adjustments-client.js" },
  { source: "src/client/today-week-ahead-client.ts", output: "public/js/today-week-ahead-client.js" },
  { source: "src/client/today-context-client.ts", output: "public/js/today-context-client.js" },
  { source: "src/client/today-compass-client.ts", output: "public/js/today-compass-client.js" },
  { source: "src/client/today-garmin-reconciliation-client.ts", output: "public/js/today-garmin-reconciliation-client.js" },
  { source: "src/client/today-side-loaders.ts", output: "public/js/today-side-loaders.js" },
  { source: "src/client/today-plan-session-model.ts", output: "public/js/today-plan-session-model.js" },
  { source: "src/client/today-plan-session-data-client.ts", output: "public/js/today-plan-session-data-client.js" },
  { source: "src/client/today-plan-session-preparation.ts", output: "public/js/today-plan-session-preparation.js" },
  { source: "src/client/today-data-loader.ts", output: "public/js/today-data-loader.js" },
  { source: "src/client/today-main-shell-client.ts", output: "public/js/today-main-shell-client.js" },
  { source: "src/client/today-plan-surface-client.ts", output: "public/js/today-plan-surface-client.js" },
  { source: "src/client/today-plan-surface-renderer.ts", output: "public/js/today-plan-surface-renderer.js" },
  { source: "src/client/today-render-state-client.ts", output: "public/js/today-render-state-client.js" },
  { source: "src/client/today-post-render-wiring.ts", output: "public/js/today-post-render-wiring.js" },
  { source: "src/client/today-dependencies.ts", output: "public/js/today-dependencies.js" },
  { source: "src/client/today-compatibility-bridges.ts", output: "public/js/today-compatibility-bridges.js" },
  { source: "src/client/today-screen-runtime-deps.ts", output: "public/js/today-screen-runtime-deps.js" },
  { source: "src/client/today-screen-runtime.ts", output: "public/js/today-screen-runtime.js" },
  { source: "src/client/today-screen.ts", output: "public/js/03-today.js" },
  { source: "src/client/progress-data-client.ts", output: "public/js/progress-data-client.js" },
  { source: "src/client/progress-endurance-client.ts", output: "public/js/progress-endurance-client.js" },
  { source: "src/client/progress-components-client.ts", output: "public/js/progress-components-client.js" },
  { source: "src/client/progress-line-chart-model.ts", output: "public/js/progress-line-chart-model.js" },
  { source: "src/client/progress-chart-scrub-client.ts", output: "public/js/progress-chart-scrub-client.js" },
  { source: "src/client/progress-chart-drawing-client.ts", output: "public/js/progress-chart-drawing-client.js" },
  { source: "src/client/progress-chart-client.ts", output: "public/js/progress-chart-client.js" },
  { source: "src/client/progress-trend-weight-client.ts", output: "public/js/progress-trend-weight-client.js" },
  { source: "src/client/progress-history-model-client.ts", output: "public/js/progress-history-model-client.js" },
  { source: "src/client/progress-history-render-client.ts", output: "public/js/progress-history-render-client.js" },
  { source: "src/client/progress-history-client.ts", output: "public/js/progress-history-client.js" },
  { source: "src/client/progress-run-plan-client.ts", output: "public/js/progress-run-plan-client.js" },
  { source: "src/client/progress-route-deps-client.ts", output: "public/js/progress-route-deps-client.js" },
  { source: "src/client/progress-endurance-controller.ts", output: "public/js/progress-endurance-controller.js" },
  { source: "src/client/progress-volume-client.ts", output: "public/js/progress-volume-client.js" },
  { source: "src/client/progress-energy-client.ts", output: "public/js/progress-energy-client.js" },
  { source: "src/client/progress-energy-surface-client.ts", output: "public/js/progress-energy-surface-client.js" },
  { source: "src/client/progress-intake-client.ts", output: "public/js/progress-intake-client.js" },
  { source: "src/client/progress-calendar-client.ts", output: "public/js/progress-calendar-client.js" },
  { source: "src/client/progress-muscle-trajectory-client.ts", output: "public/js/progress-muscle-trajectory-client.js" },
  { source: "src/client/progress-dexa-targeting-client.ts", output: "public/js/progress-dexa-targeting-client.js" },
  { source: "src/client/progress-performance-client.ts", output: "public/js/progress-performance-client.js" },
  { source: "src/client/progress-program-adjustments-client.ts", output: "public/js/progress-program-adjustments-client.js" },
  { source: "src/client/progress-test-week-client.ts", output: "public/js/progress-test-week-client.js" },
  { source: "src/client/progress-program-summary-client.ts", output: "public/js/progress-program-summary-client.js" },
  { source: "src/client/progress-program-block-client.ts", output: "public/js/progress-program-block-client.js" },
  { source: "src/client/progress-program-controller.ts", output: "public/js/progress-program-controller.js" },
  { source: "src/client/journey-progress-client.ts", output: "public/js/journey-progress-client.js" },
  { source: "src/client/journey-timeline-client.ts", output: "public/js/journey-timeline-client.js" },
  { source: "src/client/progress-overview-client.ts", output: "public/js/progress-overview-client.js" },
  { source: "src/client/body-metrics-client.ts", output: "public/js/body-metrics-client.js" },
  { source: "src/client/stand-screen.ts", output: "public/js/stand-screen.js" },
  { source: "src/client/progress-screen.ts", output: "public/js/05-progress.js" },
  { source: "src/client/capture-provenance-client.ts", output: "public/js/capture-provenance-client.js" },
  { source: "src/client/capture-read-date-client.ts", output: "public/js/capture-read-date-client.js" },
  { source: "src/client/capture-read-cards-client.ts", output: "public/js/capture-read-cards-client.js" },
  { source: "src/client/capture-read-jobs-client.ts", output: "public/js/capture-read-jobs-client.js" },
  { source: "src/client/capture-reads-client.ts", output: "public/js/capture-reads-client.js" },
  { source: "src/client/capture-voice-client.ts", output: "public/js/capture-voice-client.js" },
  { source: "src/client/capture.ts", output: "public/js/04-capture.js" },
  { source: "src/client/settings-routes.ts", output: "public/js/settings-routes.js" },
  { source: "src/client/settings-client.ts", output: "public/js/settings-client.js" },
  { source: "src/client/settings-surface-client.ts", output: "public/js/settings-surface-client.js" },
  { source: "src/client/settings-data-client.ts", output: "public/js/settings-data-client.js" },
  { source: "src/client/settings-data-controller.ts", output: "public/js/settings-data-controller.js" },
  { source: "src/client/settings-agents-client.ts", output: "public/js/settings-agents-client.js" },
  { source: "src/client/settings-agents-controller.ts", output: "public/js/settings-agents-controller.js" },
  { source: "src/client/settings-sources-automation-controller.ts", output: "public/js/settings-sources-automation-controller.js" },
  { source: "src/client/settings-screen.ts", output: "public/js/settings-screen.js" },
  { source: "src/client/chat-client.ts", output: "public/js/chat-client.js" },
  { source: "src/client/chat-attachment-client.ts", output: "public/js/chat-attachment-client.js" },
  { source: "src/client/chat-composer-focus-client.ts", output: "public/js/chat-composer-focus-client.js" },
  { source: "src/client/chat-composer-controller.ts", output: "public/js/chat-composer-controller.js" },
  { source: "src/client/chat-message-client.ts", output: "public/js/chat-message-client.js" },
  { source: "src/client/chat-turn-records-client.ts", output: "public/js/chat-turn-records-client.js" },
  { source: "src/client/chat-turn-stream-state-client.ts", output: "public/js/chat-turn-stream-state-client.js" },
  { source: "src/client/chat-layout-client.ts", output: "public/js/chat-layout-client.js" },
  { source: "src/client/chat-turn-monitor-client.ts", output: "public/js/chat-turn-monitor-client.js" },
  { source: "src/client/chat-turn-client.ts", output: "public/js/chat-turn-client.js" },
  { source: "src/client/chat-history-client.ts", output: "public/js/chat-history-client.js" },
  { source: "src/client/chat-header-controller.ts", output: "public/js/chat-header-controller.js" },
  { source: "src/client/chat-starter-chips-client.ts", output: "public/js/chat-starter-chips-client.js" },
  { source: "src/client/chat-fuel-context-client.ts", output: "public/js/chat-fuel-context-client.js" },
  { source: "src/client/chat-earlier-history-client.ts", output: "public/js/chat-earlier-history-client.js" },
  { source: "src/client/plan-endurance-model.ts", output: "public/js/plan-endurance-model.js" },
  { source: "src/client/plan-endurance-client.ts", output: "public/js/plan-endurance-client.js" },
  { source: "src/client/plan-editor-client.ts", output: "public/js/plan-editor-client.js" },
  { source: "src/client/plan-editor-form-client.ts", output: "public/js/plan-editor-form-client.js" },
  { source: "src/client/plan-editor-controller.ts", output: "public/js/plan-editor-controller.js" },
  { source: "src/client/chat-screen.ts", output: "public/js/09-plan-chat.js" },
  { source: "src/client/day-fuel-client.ts", output: "public/js/day-fuel-client.js" },
  { source: "src/client/day-fuel-controller.ts", output: "public/js/day-fuel-controller.js" },
  { source: "src/client/meal-row-client.ts", output: "public/js/meal-row-client.js" },
  { source: "src/client/meal-plan-client.ts", output: "public/js/meal-plan-client.js" },
  { source: "src/client/meal-planner-jobs-client.ts", output: "public/js/meal-planner-jobs-client.js" },
  { source: "src/client/meal-recipe-client.ts", output: "public/js/meal-recipe-client.js" },
  { source: "src/client/meal-recipe-controller.ts", output: "public/js/meal-recipe-controller.js" },
  { source: "src/client/meal-swap-data-client.ts", output: "public/js/meal-swap-data-client.js" },
  { source: "src/client/meal-swap-row-actions-controller.ts", output: "public/js/meal-swap-row-actions-controller.js" },
  { source: "src/client/meal-swap-controller.ts", output: "public/js/meal-swap-controller.js" },
  { source: "src/client/meal-planner-actions-controller.ts", output: "public/js/meal-planner-actions-controller.js" },
  { source: "src/client/meal-planner-controller.ts", output: "public/js/meal-planner-controller.js" },
  { source: "src/client/coach-proposal-controller.ts", output: "public/js/coach-proposal-controller.js" },
  { source: "src/client/coach-meals-screen.ts", output: "public/js/06-coach-meals.js" },
  { source: "src/client/food-note-client.ts", output: "public/js/food-note-client.js" },
  { source: "src/client/food-detail-controller.ts", output: "public/js/food-detail-controller.js" },
  { source: "src/client/me-profile-form-client.ts", output: "public/js/me-profile-form-client.js" },
  { source: "src/client/me-profile-controller.ts", output: "public/js/me-profile-controller.js" },
  { source: "src/client/me-health-log-renderer.ts", output: "public/js/me-health-log-renderer.js" },
  { source: "src/client/me-health-tabs-controller.ts", output: "public/js/me-health-tabs-controller.js" },
  { source: "src/client/me-health-controller-deps.ts", output: "public/js/me-health-controller-deps.js" },
  { source: "src/client/me-health-dependencies.ts", output: "public/js/me-health-dependencies.js" },
  { source: "src/client/health-evidence-client.ts", output: "public/js/health-evidence-client.js" },
  { source: "src/client/health-marker-order-client.ts", output: "public/js/health-marker-order-client.js" },
  { source: "src/client/health-client.ts", output: "public/js/health-client.js" },
  { source: "src/client/health-read-client.ts", output: "public/js/health-read-client.js" },
  { source: "src/client/health-standing-primitives-client.ts", output: "public/js/health-standing-primitives-client.js" },
  { source: "src/client/health-standing-client.ts", output: "public/js/health-standing-client.js" },
  { source: "src/client/health-standing-controller.ts", output: "public/js/health-standing-controller.js" },
  { source: "src/client/health-risk-client.ts", output: "public/js/health-risk-client.js" },
  { source: "src/client/health-risk-controller.ts", output: "public/js/health-risk-controller.js" },
  { source: "src/client/health-picture-client.ts", output: "public/js/health-picture-client.js" },
  { source: "src/client/health-picture-controller.ts", output: "public/js/health-picture-controller.js" },
  { source: "src/client/health-markers-client.ts", output: "public/js/health-markers-client.js" },
  { source: "src/client/health-markers-controller.ts", output: "public/js/health-markers-controller.js" },
  { source: "src/client/health-directives-client.ts", output: "public/js/health-directives-client.js" },
  { source: "src/client/health-directives-loader-client.ts", output: "public/js/health-directives-loader-client.js" },
  { source: "src/client/health-read-synthesis-client.ts", output: "public/js/health-read-synthesis-client.js" },
  { source: "src/client/health-read-supplements-client.ts", output: "public/js/health-read-supplements-client.js" },
  { source: "src/client/health-read-controller.ts", output: "public/js/health-read-controller.js" },
  { source: "src/client/health-learned-client.ts", output: "public/js/health-learned-client.js" },
  { source: "src/client/health-checkup-client.ts", output: "public/js/health-checkup-client.js" },
  { source: "src/client/health-records-client.ts", output: "public/js/health-records-client.js" },
  { source: "src/client/imaging-upload-model.ts", output: "public/js/imaging-upload-model.js" },
  { source: "src/client/dicom-viewer-model.ts", output: "public/js/dicom-viewer-model.js" },
  { source: "src/client/dicom-viewer-controller.ts", output: "public/js/dicom-viewer-controller.js" },
  { source: "src/client/imaging-client.ts", output: "public/js/imaging-client.js" },
  { source: "src/client/health-doc-upload-controller.ts", output: "public/js/health-doc-upload-controller.js" },
  { source: "src/client/health-doc-date-actions-client.ts", output: "public/js/health-doc-date-actions-client.js" },
  { source: "src/client/health-doc-lifecycle-actions-client.ts", output: "public/js/health-doc-lifecycle-actions-client.js" },
  { source: "src/client/health-doc-actions-controller.ts", output: "public/js/health-doc-actions-controller.js" },
  { source: "src/client/me-records-health-doc-controller.ts", output: "public/js/me-records-health-doc-controller.js" },
  { source: "src/client/health-share-controller.ts", output: "public/js/health-share-controller.js" },
  { source: "src/client/memory-client.ts", output: "public/js/memory-client.js" },
  { source: "src/client/me-memory-controller.ts", output: "public/js/me-memory-controller.js" },
  { source: "src/client/life-client.ts", output: "public/js/life-client.js" },
  { source: "src/client/life-form-helpers.ts", output: "public/js/life-form-helpers.js" },
  { source: "src/client/life-timeline-actions.ts", output: "public/js/life-timeline-actions.js" },
  { source: "src/client/life-controller.ts", output: "public/js/life-controller.js" },
  { source: "src/client/family-client.ts", output: "public/js/family-client.js" },
  { source: "src/client/family-controller.ts", output: "public/js/family-controller.js" },
  { source: "src/client/me-health-screen-composition.ts", output: "public/js/me-health-screen-composition.js" },
  { source: "src/client/me-health-screen.ts", output: "public/js/07-me-health.js" },
  { source: "src/client/me-records-screen.ts", output: "public/js/08-me-records.js" },
  { source: "src/client/health-docs-client.ts", output: "public/js/health-docs-client.js" },
  { source: "src/client/route-state.ts", output: "public/js/route-state.js" },
  { source: "src/client/app/router.ts", output: "public/js/app-router.js" },
  { source: "src/client/app/route-sync.ts", output: "public/js/app-route-sync.js" },
  { source: "src/client/app/render-dispatch.ts", output: "public/js/app-render-dispatch.js" },
  { source: "src/client/app/tabs.ts", output: "public/js/app-tabs.js" },
  { source: "src/client/app/job-reconnectors.ts", output: "public/js/app-job-reconnectors.js" },
  { source: "src/client/app/mobile-viewport.ts", output: "public/js/app-mobile-viewport.js" },
  { source: "src/client/app/day-rollover.ts", output: "public/js/app-day-rollover.js" },
  { source: "src/client/app/service-worker.ts", output: "public/js/app-service-worker.js" },
  { source: "src/client/app/discipline-primer.ts", output: "public/js/app-discipline-primer.js" },
  { source: "src/client/app/onboarding.ts", output: "public/js/app-onboarding.js" },
  { source: "src/client/app/startup.ts", output: "public/js/app-startup.js" },
];

// Ordered concatenation manifest. index.html loads a handful of bundles instead
// of ~216 individual <script>s (a big cold-start win: far fewer request round
// trips). Each bundle is the in-order concatenation of the already-built,
// IIFE-wrapped individual outputs above, so global scope and load order are
// unchanged. The CONCATENATION OF EVERY BUNDLE'S `inputs`, IN THIS ARRAY ORDER,
// REPRODUCES THE CANONICAL <script> SEQUENCE EXACTLY — this manifest is now the
// authoritative encoding of that order. Every CLIENT_OUTPUTS output (plus the
// hand-written classic shim public/js/10-boot.js) appears in exactly one bundle.
//
// Splitting the larger bundles further was evaluated and DECLINED: `defer` on
// the <script> tags already unblocked first paint, the IIFE shared-global model
// makes any reshape a load-order hazard, and a bundle reshape re-enters the
// breakage class that bit the last shell reshape (smoke assertions, the
// Dockerfile COPY list, the deploy health check) for a marginal win. Revisit
// only alongside a move to real ES modules.
export const BUNDLES = [
  {
    output: "public/js/bundle-01-core.js",
    label: "foundations (utils, api, core state, ui shell)",
    inputs: [
      "public/js/date-utils.js",
      "public/js/html-utils.js",
      "public/js/markdown-client.js",
      "public/js/ui-components.js",
      "public/js/ui-reads.js",
      "public/js/ui-feedback-client.js",
      "public/js/ui-actions-client.js",
      "public/js/ui-view-transitions-client.js",
      "public/js/exercise-detail-client.js",
      "public/js/format-utils.js",
      "public/js/client-diagnostics.js",
      "public/js/api-client.js",
      "public/js/app-download.js",
      "public/js/app-sw-recovery.js",
      "public/js/01-core.js",
      "public/js/art-controller.js",
      "public/js/pwa-install-coach.js",
      "public/js/ui-header-client.js",
      "public/js/ui-segments-client.js",
      "public/js/02-ui.js",
    ],
  },
  {
    output: "public/js/bundle-02-today.js",
    label: "Today screen + Progress infrastructure",
    inputs: [
      "public/js/detail-overlay-client.js",
      "public/js/ui-motion-client.js",
      "public/js/exercise-detail-data-client.js",
      "public/js/exercise-detail-explanation-client.js",
      "public/js/exercise-detail-render-client.js",
      "public/js/exercise-detail-actions-client.js",
      "public/js/exercise-detail-controller.js",
      "public/js/agent-login-model-client.js",
      "public/js/agent-login-assets-client.js",
      "public/js/agent-login-modal-client.js",
      "public/js/agent-login-session-client.js",
      "public/js/agent-login-client.js",
      "public/js/agent-job-records-client.js",
      "public/js/agent-job-client.js",
      "public/js/rest-timer.js",
      "public/js/coaching-focus-client.js",
      "public/js/today-activity-client.js",
      "public/js/save-bar.js",
      "public/js/swr-cache.js",
      "public/js/today-agenda-client.js",
      "public/js/today-rail-loaders-client.js",
      "public/js/today-rail-controller.js",
      "public/js/today-plan-selection-client.js",
      "public/js/today-training-client.js",
      "public/js/today-progression-controller.js",
      "public/js/today-add-exercise-controller.js",
      "public/js/today-brief-client.js",
      "public/js/today-brief-override-client.js",
      "public/js/today-brief-actions-client.js",
      "public/js/today-brief-controller.js",
      "public/js/cardio-plan-client.js",
      "public/js/cardio-sync-client.js",
      "public/js/today-lately-client.js",
      "public/js/proposal-client.js",
      "public/js/today-session-suggest-client.js",
      "public/js/today-session-suggest-controller.js",
      "public/js/today-session-status-client.js",
      "public/js/today-session-feedback-client.js",
      "public/js/session-primer-client.js",
      "public/js/today-session-skip-client.js",
      "public/js/today-session-set-model.js",
      "public/js/today-session-set-actions.js",
      "public/js/today-session-controller.js",
      "public/js/today-cards-client.js",
      "public/js/today-program-adjustments-client.js",
      "public/js/today-week-ahead-client.js",
      "public/js/today-context-client.js",
      "public/js/today-compass-client.js",
      "public/js/today-garmin-reconciliation-client.js",
      "public/js/today-side-loaders.js",
      "public/js/today-plan-session-model.js",
      "public/js/today-plan-session-data-client.js",
      "public/js/today-plan-session-preparation.js",
      "public/js/today-data-loader.js",
      "public/js/today-main-shell-client.js",
      "public/js/today-plan-surface-client.js",
      "public/js/today-plan-surface-renderer.js",
      "public/js/today-render-state-client.js",
      "public/js/today-post-render-wiring.js",
      "public/js/today-dependencies.js",
      "public/js/today-compatibility-bridges.js",
      "public/js/today-screen-runtime-deps.js",
      "public/js/today-screen-runtime.js",
      "public/js/progress-data-client.js",
      "public/js/progress-endurance-client.js",
      "public/js/progress-components-client.js",
      "public/js/progress-line-chart-model.js",
      "public/js/progress-chart-scrub-client.js",
      "public/js/progress-chart-drawing-client.js",
      "public/js/progress-chart-client.js",
      "public/js/progress-trend-weight-client.js",
      "public/js/progress-history-model-client.js",
      "public/js/progress-history-render-client.js",
      "public/js/progress-history-client.js",
      "public/js/progress-run-plan-client.js",
      "public/js/progress-route-deps-client.js",
      "public/js/progress-endurance-controller.js",
      "public/js/progress-volume-client.js",
      "public/js/progress-energy-client.js",
      "public/js/progress-energy-surface-client.js",
      "public/js/progress-intake-client.js",
      "public/js/progress-calendar-client.js",
      "public/js/progress-muscle-trajectory-client.js",
      "public/js/progress-dexa-targeting-client.js",
      "public/js/progress-performance-client.js",
      "public/js/progress-program-adjustments-client.js",
      "public/js/progress-test-week-client.js",
      "public/js/progress-program-summary-client.js",
      "public/js/progress-program-block-client.js",
      "public/js/progress-program-controller.js",
      "public/js/journey-progress-client.js",
      "public/js/journey-timeline-client.js",
      "public/js/progress-overview-client.js",
      "public/js/03-today.js",
    ],
  },
  {
    output: "public/js/bundle-03-capture-progress.js",
    label: "capture + Progress screen",
    inputs: [
      "public/js/capture-provenance-client.js",
      "public/js/capture-read-date-client.js",
      "public/js/capture-read-cards-client.js",
      "public/js/capture-read-jobs-client.js",
      "public/js/capture-reads-client.js",
      "public/js/capture-voice-client.js",
      "public/js/04-capture.js",
      "public/js/body-metrics-client.js",
      "public/js/05-progress.js",
    ],
  },
  {
    output: "public/js/bundle-04-coach-meals.js",
    label: "coach proposals + meal planner",
    inputs: [
      "public/js/day-fuel-client.js",
      "public/js/day-fuel-controller.js",
      "public/js/meal-row-client.js",
      "public/js/meal-plan-client.js",
      "public/js/meal-planner-jobs-client.js",
      "public/js/meal-recipe-client.js",
      "public/js/meal-recipe-controller.js",
      "public/js/meal-swap-data-client.js",
      "public/js/meal-swap-row-actions-controller.js",
      "public/js/meal-swap-controller.js",
      "public/js/meal-planner-actions-controller.js",
      "public/js/meal-planner-controller.js",
      "public/js/coach-proposal-controller.js",
      "public/js/06-coach-meals.js",
    ],
  },
  {
    output: "public/js/bundle-05-me-health.js",
    label: "Me / Health / Records",
    inputs: [
      "public/js/food-note-client.js",
      "public/js/food-detail-controller.js",
      "public/js/health-docs-client.js",
      "public/js/me-profile-form-client.js",
      "public/js/me-profile-controller.js",
      "public/js/me-health-log-renderer.js",
      "public/js/me-health-tabs-controller.js",
      "public/js/me-health-controller-deps.js",
      "public/js/me-health-dependencies.js",
      "public/js/me-health-screen-composition.js",
      "public/js/07-me-health.js",
      "public/js/health-evidence-client.js",
      "public/js/health-marker-order-client.js",
      "public/js/health-client.js",
      "public/js/health-read-client.js",
      "public/js/health-standing-primitives-client.js",
      "public/js/health-standing-client.js",
      "public/js/health-standing-controller.js",
      "public/js/health-risk-client.js",
      "public/js/health-risk-controller.js",
      "public/js/health-picture-client.js",
      "public/js/health-picture-controller.js",
      "public/js/health-markers-client.js",
      "public/js/health-markers-controller.js",
      "public/js/stand-screen.js",
      "public/js/health-directives-client.js",
      "public/js/health-directives-loader-client.js",
      "public/js/health-read-synthesis-client.js",
      "public/js/health-read-supplements-client.js",
      "public/js/health-read-controller.js",
      "public/js/health-learned-client.js",
      "public/js/health-checkup-client.js",
      "public/js/health-records-client.js",
      "public/js/imaging-upload-model.js",
      "public/js/dicom-viewer-model.js",
      "public/js/dicom-viewer-controller.js",
      "public/js/imaging-client.js",
      "public/js/health-doc-upload-controller.js",
      "public/js/health-doc-date-actions-client.js",
      "public/js/health-doc-lifecycle-actions-client.js",
      "public/js/health-doc-actions-controller.js",
      "public/js/me-records-health-doc-controller.js",
      "public/js/health-share-controller.js",
      "public/js/memory-client.js",
      "public/js/me-memory-controller.js",
      "public/js/life-client.js",
      "public/js/life-form-helpers.js",
      "public/js/life-timeline-actions.js",
      "public/js/life-controller.js",
      "public/js/family-client.js",
      "public/js/family-controller.js",
      "public/js/08-me-records.js",
    ],
  },
  {
    output: "public/js/bundle-06-chat-plan.js",
    label: "Chat + Plan editor",
    inputs: [
      "public/js/chat-client.js",
      "public/js/chat-attachment-client.js",
      "public/js/chat-composer-focus-client.js",
      "public/js/chat-composer-controller.js",
      "public/js/chat-message-client.js",
      "public/js/chat-turn-records-client.js",
      "public/js/chat-turn-stream-state-client.js",
      "public/js/chat-layout-client.js",
      "public/js/chat-turn-monitor-client.js",
      "public/js/chat-turn-client.js",
      "public/js/chat-history-client.js",
      "public/js/chat-header-controller.js",
      "public/js/chat-starter-chips-client.js",
      "public/js/chat-fuel-context-client.js",
      "public/js/chat-earlier-history-client.js",
      "public/js/plan-endurance-model.js",
      "public/js/plan-endurance-client.js",
      "public/js/plan-editor-client.js",
      "public/js/plan-editor-form-client.js",
      "public/js/plan-editor-controller.js",
      "public/js/09-plan-chat.js",
    ],
  },
  {
    output: "public/js/bundle-07-settings-boot.js",
    label: "Settings + app router + boot",
    inputs: [
      "public/js/settings-routes.js",
      "public/js/settings-client.js",
      "public/js/settings-surface-client.js",
      "public/js/settings-data-client.js",
      "public/js/settings-data-controller.js",
      "public/js/settings-agents-client.js",
      "public/js/settings-agents-controller.js",
      "public/js/settings-sources-automation-controller.js",
      "public/js/settings-screen.js",
      "public/js/route-state.js",
      "public/js/app-router.js",
      "public/js/app-route-sync.js",
      "public/js/app-render-dispatch.js",
      "public/js/app-tabs.js",
      "public/js/app-job-reconnectors.js",
      "public/js/app-mobile-viewport.js",
      "public/js/app-day-rollover.js",
      "public/js/app-service-worker.js",
      "public/js/app-discipline-primer.js",
      "public/js/app-onboarding.js",
      "public/js/app-startup.js",
      "public/js/10-boot.js",
    ],
  },
];

const compilerOptions = {
  alwaysStrict: false,
  ignoreDeprecations: "6.0",
  module: ts.ModuleKind.None,
  moduleDetection: ts.ModuleDetectionKind.Legacy,
  removeComments: false,
  target: ts.ScriptTarget.ES2022,
};

function wrapClassicScript(source) {
  return `(() => {\n${source.trimEnd()}\n})();\n`;
}

function bundleHeader(label) {
  return (
    "// GENERATED by scripts/build-client.mjs — do not edit.\n" +
    "// Ordered concatenation of individual public/js modules (see the BUNDLES\n" +
    "// manifest). The classic <script> load order is preserved exactly and each\n" +
    "// constituent stays IIFE-wrapped, so global scope is unchanged.\n" +
    `// Bundle: ${label}\n`
  );
}

// Concatenate the already-built individual outputs, in manifest order, into the
// handful of bundle files index.html actually loads. Reads what buildClient()
// just wrote, so this must run AFTER the per-file emit.
export function buildBundles() {
  for (const bundle of BUNDLES) {
    const chunks = bundle.inputs.map((input) => {
      const body = readFileSync(path.join(root, input), "utf8").trimEnd();
      return `// ==== ${input} ====\n${body}`;
    });
    const content = `${bundleHeader(bundle.label)}\n${chunks.join("\n;\n")}\n`;
    const outputPath = path.join(root, bundle.output);
    mkdirSync(path.dirname(outputPath), { recursive: true });
    writeFileSync(outputPath, content);
  }
  console.log(`✓ built client bundles (${BUNDLES.length} bundle${BUNDLES.length === 1 ? "" : "s"})`);
}

export function buildClient() {
  for (const item of CLIENT_OUTPUTS) {
    const sourcePath = path.join(root, item.source);
    const outputPath = path.join(root, item.output);
    const source = readFileSync(sourcePath, "utf8");
    const result = ts.transpileModule(source, {
      compilerOptions,
      fileName: item.source,
      reportDiagnostics: true,
    });
    const diagnostics = result.diagnostics?.filter((d) => d.category === ts.DiagnosticCategory.Error) ?? [];
    if (diagnostics.length) {
      const msg = ts.formatDiagnosticsWithColorAndContext(diagnostics, {
        getCanonicalFileName: (file) => file,
        getCurrentDirectory: () => root,
        getNewLine: () => "\n",
      });
      console.error(msg);
      process.exit(1);
    }
    mkdirSync(path.dirname(outputPath), { recursive: true });
    writeFileSync(outputPath, wrapClassicScript(result.outputText));
  }

  console.log(`✓ built client output (${CLIENT_OUTPUTS.length} file${CLIENT_OUTPUTS.length === 1 ? "" : "s"})`);
  buildBundles();
}

if (process.argv[1] && path.resolve(process.argv[1]) === currentFile) {
  buildClient();
}
