#!/usr/bin/env node
// Concatenate the stylesheet partials under src/styles/ into public/styles.css.
//
// The app ships ONE stylesheet (index.html links it, the service worker precaches
// it, the build precompresses it), but it is authored as per-surface partials so a
// screen stream edits only the files it owns (docs/DESIGN.md "Stylesheet ownership").
// The ORDER below is the cascade: a later partial wins a same-specificity tie, so a
// partial never moves without reading what it would now override. Every .css file
// under src/styles/ must appear here exactly once; an unlisted or missing partial
// fails the build rather than silently dropping rules.
//
// public/styles.css stays committed (the Docker runtime stage and the test suite
// read it straight from the checkout), so `--check` (run by `npm run verify`) fails
// when the committed file drifts from its partials.
//
// Usage: node scripts/build-styles.mjs [--check | --watch]
//   --watch rebuilds on every partial save (`npm run styles:watch`, next to `npm run dev`).
import { existsSync, readdirSync, readFileSync, watch, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const currentFile = fileURLToPath(import.meta.url);
const root = path.resolve(path.dirname(currentFile), "..");

export const STYLES_DIR = "src/styles";
export const STYLES_OUTPUT = "public/styles.css";

/** The cascade order. Foundation first, then the surfaces in their historical order. */
export const STYLE_PARTIALS = [
  "foundation/tokens",
  "foundation/fonts",
  "foundation/base",
  "foundation/motion",
  "foundation/primitives",
  "foundation/stones",
  "foundation/cards",
  "foundation/components",
  "today/header",
  "session/exercise",
  "foundation/segments",
  "train/plan-editor",
  "train/progress",
  "fuel/meal-plans",
  "ask/chat",
  "settings/settings",
  "you/records",
  "shell/overlays",
  "shell/tabbar",
  "shell/responsive-nav",
  "shell/detail",
  "fuel/planner",
  "today/date",
  "fuel/meal-sheet",
  "train/progress-editorial",
  "today/garmin",
  "today/brief",
  "foundation/loading",
  "ask/capture",
  "settings/groups",
  "foundation/reduced-motion",
  "health/health",
  "health/stand",
  "you/profile",
  "shell/responsive",
  "train/endurance",
  "foundation/a11y",
  "train/program",
  "train/strength",
  "session/destination",
  "train/overview",
  "ask/changes",
  "fuel/meal-card",
  "fuel/today",
  "health/records",
  "health/packet",
  "horizon/race",
  "today/pebbles",
  "today/path",
  "today/ahead",
  "today/day",
  "today/day-detail",
  "you/cairn",
  "shell/identity",
  "shell/nav",
  "ask/ask",
  "horizon/horizon",
  "horizon/week",
  // The first-run welcome, the AI sign-in panel it shares with Settings, and the
  // coach link's quiet cards on Today and Ask.
  "welcome/coach-link",
  "welcome/connect",
  "welcome/welcome",
];

const BANNER =
  "/* GENERATED by scripts/build-styles.mjs from src/styles/** (minified). Edit the partials, never this file.\n" +
  "   Cascade order and ownership: docs/DESIGN.md \"Stylesheet ownership\". */\n";

function listPartials(dir = STYLES_DIR) {
  const out = [];
  const abs = path.join(root, dir);
  if (!existsSync(abs)) return out;
  for (const entry of readdirSync(abs, { withFileTypes: true })) {
    const rel = `${dir}/${entry.name}`;
    if (entry.isDirectory()) out.push(...listPartials(rel));
    else if (entry.name.endsWith(".css")) out.push(rel.slice(STYLES_DIR.length + 1, -".css".length));
  }
  return out;
}

/**
 * Conservative CSS minification: comments dropped (an empty one kept where it glues
 * two tokens), whitespace runs collapsed to one
 * space, and the space next to `{`, `}`, `;` and `,` (where CSS never needs it)
 * removed, plus the redundant `;` before a `}`. Strings and unquoted url(...)
 * bodies are copied verbatim, and a custom property's value keeps its spacing
 * (it is a raw token stream that script may read back with getPropertyValue). Nothing is reordered, merged or rewritten, and the
 * space that CAN matter (descendant combinators, `calc(a + b)`, `and (`, a colon
 * in a selector) is kept as one space. One rule per line keeps the committed file
 * reviewable and merge-friendly; the partials under src/styles/ keep every comment.
 */
export function minifyCss(css) {
  let out = "";
  let pendingSpace = false;
  // Custom-property state: where the current declaration started in `out`, the
  // paren depth, and whether we are inside a `--name:` value.
  let declStart = 0;
  let depth = 0;
  let inCustom = false;
  const n = css.length;
  const tight = (ch) => ch === "{" || ch === "}" || ch === ";" || (ch === "," && !inCustom) || ch === "\n";
  const emit = (text) => {
    if (pendingSpace && out.length && !tight(out[out.length - 1]) && !tight(text[0])) out += " ";
    pendingSpace = false;
    out += text;
  };
  let i = 0;
  while (i < n) {
    const ch = css[i];
    if (ch === "/" && css[i + 1] === "*") {
      const end = css.indexOf("*/", i + 2);
      i = end < 0 ? n : end + 2;
      // A comment is NOT whitespace: `.a/**/.b` is the compound `.a.b`, and
      // `1px/**/solid` is two tokens. Glued between two token characters it
      // stays as an empty `/**/`; next to whitespace or punctuation it just goes.
      const prev = pendingSpace ? " " : out[out.length - 1] || " ";
      const next = css[i] || " ";
      const glue = (c) => !/[\s{};,]/.test(c);
      if (glue(prev) && glue(next)) out += "/**/";
      continue;
    }
    if (ch === '"' || ch === "'") {
      let j = i + 1;
      while (j < n && css[j] !== ch) j += css[j] === "\\" ? 2 : 1;
      emit(css.slice(i, j + 1));
      i = j + 1;
      continue;
    }
    if ((ch === "u" || ch === "U") && /^url\(\s*[^\s"')]/i.test(css.slice(i, i + 6)) && !/[\w-]/.test(css[i - 1] || "")) {
      const end = css.indexOf(")", i);
      emit(css.slice(i, end + 1));
      i = end + 1;
      continue;
    }
    if (/\s/.test(ch)) {
      pendingSpace = true;
      i += 1;
      continue;
    }
    if (ch === "," && inCustom) {
      emit(ch);
      i += 1;
      continue;
    }
    if (ch === "{" || ch === ";" || ch === ",") {
      pendingSpace = false;
      out += ch;
      i += 1;
      if (ch !== "," && depth === 0) {
        inCustom = false;
        declStart = out.length;
      }
      continue;
    }
    if (ch === "}") {
      pendingSpace = false;
      if (out.endsWith(";")) out = out.slice(0, -1);
      out += "}\n";
      i += 1;
      depth = 0;
      inCustom = false;
      declStart = out.length;
      continue;
    }
    if (ch === "(") depth += 1;
    else if (ch === ")") depth = Math.max(0, depth - 1);
    else if (ch === ":" && depth === 0 && !inCustom && out.slice(declStart).trimStart().startsWith("--")) inCustom = true;
    emit(ch);
    i += 1;
  }
  return out;
}

/** The stylesheet the partials produce, or throws naming the partials out of step. */
export function renderStyles() {
  const onDisk = new Set(listPartials());
  const listed = new Set(STYLE_PARTIALS);
  const problems = [];
  if (listed.size !== STYLE_PARTIALS.length) problems.push("a partial is listed twice in STYLE_PARTIALS");
  for (const name of STYLE_PARTIALS) if (!onDisk.has(name)) problems.push(`listed but missing: ${STYLES_DIR}/${name}.css`);
  for (const name of onDisk) if (!listed.has(name)) problems.push(`not in STYLE_PARTIALS: ${STYLES_DIR}/${name}.css`);
  if (problems.length) throw new Error(`stylesheet partials out of step:\n  ${problems.join("\n  ")}`);
  let css = "";
  for (const name of STYLE_PARTIALS) {
    const chunk = readFileSync(path.join(root, STYLES_DIR, `${name}.css`), "utf8");
    css += chunk.endsWith("\n") ? chunk : `${chunk}\n`;
  }
  return BANNER + minifyCss(css);
}

export function buildStyles() {
  const css = renderStyles();
  const target = path.join(root, STYLES_OUTPUT);
  const before = existsSync(target) ? readFileSync(target, "utf8") : null;
  if (before !== css) writeFileSync(target, css);
  console.log(`✓ built ${STYLES_OUTPUT} from ${STYLE_PARTIALS.length} partials (${(css.length / 1024).toFixed(0)} KB)`);
}

export function checkStyles() {
  const css = renderStyles();
  const target = path.join(root, STYLES_OUTPUT);
  const committed = existsSync(target) ? readFileSync(target, "utf8") : "";
  if (committed !== css) {
    console.error(`✗ ${STYLES_OUTPUT} is out of date with ${STYLES_DIR}/. Run: node scripts/build-styles.mjs`);
    process.exit(1);
  }
  console.log(`✓ ${STYLES_OUTPUT} matches its ${STYLE_PARTIALS.length} partials`);
}

/** Rebuild on every partial save; a bad state is reported and waited out, never fatal. */
export function watchStyles() {
  const rebuild = () => {
    try {
      buildStyles();
    } catch (error) {
      console.error(`✗ ${error instanceof Error ? error.message : String(error)}`);
    }
  };
  rebuild();
  let timer = null;
  watch(path.join(root, STYLES_DIR), { recursive: true }, () => {
    clearTimeout(timer);
    timer = setTimeout(rebuild, 60);
  });
  console.log(`… watching ${STYLES_DIR}/ for changes`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === currentFile) {
  try {
    if (process.argv.includes("--check")) checkStyles();
    else if (process.argv.includes("--watch")) watchStyles();
    else buildStyles();
  } catch (error) {
    console.error(`✗ ${error instanceof Error ? error.message : String(error)}`);
    process.exit(1);
  }
}
